# Green Deployment (The New Version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      env: green # Using 'env' label for the switch
  template:
    metadata:
      labels:
        app: aceest-fitness
        env: green
    spec:
      containers:
      - name: aceest-fitness-app
        # Jenkins will replace VERSION_TAG with the actual build number
        image: svkris/aceest-fitness-gym-cicd:VERSION_TAG 
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5

---
# The Shared Service (The Router)
apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-service
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    env: blue # Initially points to blue; Jenkins will patch this to 'green'
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001